# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - run: npm install
      - run: npm run test

workflows:
  test:
    jobs:
      - test