# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: npm run test

  release:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: npx semantic-release


workflows:
  test:
    jobs:
      - test
      - release:
          filters:
            branches:
              only: master
          requires:
            - test